PJATK-SPK/ingoodhands

src/backend/AuthService/BusinessLogic/PostLogin/PostLoginAction.cs, src/backend/Core/WebApi/WebApiBuilder.cs, src/frontend/src/app/app.component.ts
Fixing JSON serialization loop
=> Fix JSON serialization loop

.github/workflows/sonar.yml
=> feat(infra): add sonar in ci

src/backend/Core/ConfigSetup/ConfigurationReader.cs, src/backend/WebApi/Controllers/AuthController.cs
=> Get db credentials from environment variables

src/backend/Core/WebApi/WebApiBuilder.cs
=> Fix swagger on prod

.github/workflows/build-fe.yml, .github/workflows/deploy-be.yml, .github/workflows/deploy-fe.yml, infra/terraform/modules/ingoodhands/modules/basics/db.tf
- [] Bug fix (non-breaking change which fixes an issue)
=> feat(infra): add db migration

.github/workflows/build-be.yml, .github/workflows/deploy-be.yml, .github/workflows/sonar.yml
- [] New feature (non-breaking change which adds functionality)
=> feat(infra): add prod db env variables

.github/workflows/build-be.yml, .github/workflows/build-fe.yml, src/frontend/angular.json
- [] New feature (non-breaking change which adds functionality)
=> feat(infra): fix frontend

.github/workflows/sonar.yml
- [] New feature (non-breaking change which adds functionality)
=> feat(infra): disable sonar

src/frontend/src/app/pages/home/home.component.html
- [] Bug fix (non-breaking change which fixes an issue)
=> Change landing page texts

.github/workflows/deploy-fe.yml
- [] New feature (non-breaking change which adds functionality)
=> feat(infra): fix fe deploy

sonar-project.properties, src/backend/AuthServiceTests/BusinessLogic/PostLogin/PostLoginActionTests.cs, src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Base/DbEntity.cs, src/backend/Core/Database/Config/Models/CountryConfig.cs, src/backend/Core/Database/Models/Auth0User.cs, src/backend/Core/Database/Models/Country.cs, src/backend/Core/Database/Models/Permission.cs, src/backend/Core/Database/Models/Role.cs, src/backend/Core/Database/Models/RolePermission.cs, src/backend/Core/Database/Models/User.cs, src/backend/Core/Migrations/20230201201506_AddCountry.Designer.cs, src/backend/Core/Migrations/20230201201506_AddCountry.cs
=> Add countries table

src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Config/Models/AddressConfig.cs, src/backend/Core/Database/Models/Address.cs, src/backend/Core/Database/Models/Country.cs, src/backend/Core/Migrations/20230201213522_AddAddress.Designer.cs, src/backend/Core/Migrations/20230201213522_AddAddress.cs
=> Add address

.github/actions/sonar/action.yml, .github/workflows/deploy-be.yml
=> feat(infra): fix sonar coverage main

src/backend/AuthService/BusinessLogic/PostLogin/UserCreationService.cs, src/backend/Core/CoreModule.cs, src/backend/Core/Database/Base/DbEntity.cs, src/backend/Core/Database/Models/User.cs, src/backend/Core/WebApi/WebApiBuilder.cs, src/backend/Tests.Core/TestsToolkit.cs, src/backend/WebApi/Controllers/MaintenanceController.cs, src/backend/WebApi/Program.cs, src/backend/WebApi/UsedModules.cs, src/backend/Worker/UsedModules.cs, src/frontend/src/app/pages/home/donate/stepper/services/step-1.service.ts
=> Sonarcloud

.github/actions/sonar/action.yml
=> Merge Sonar reports

.github/workflows/build-test-all.yml, .github/workflows/deploy-fe.yml, src/frontend/sonar-project.properties
=> feat(infra): add angular scan

src/backend/AuthService/Actions/AuthActions/PostLogin/UserCreationService.cs, src/backend/AuthServiceTests/Actions/AuthActionsTest/PostLogin/PostLoginActionTests.cs, src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Enums/RoleName.cs, src/backend/Core/Database/Seeders/RoleSeeder.cs, src/backend/Core/Migrations/20230207165532_SeedingRoles.Designer.cs, src/backend/Core/Migrations/20230207165532_SeedingRoles.cs
=> Adding Donor Role whilst creating ANY user /added seedRole migration to db

src/backend/.gitignore, src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Config/Models/Core/WarehouseConfig.cs, src/backend/Core/Database/Models/Core/Address.cs, src/backend/Core/Database/Models/Core/Warehouse.cs, src/backend/Core/Migrations/20230208184157_AddWarehouse.Designer.cs, src/backend/Core/Migrations/20230208184157_AddWarehouse.cs
=> Cu 862j535ru migration   table structure marcel pankanin

.github/actions/deploy-be/action.yml, src/backend/Core/Core.csproj, src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Seeders/ProductSeeder.cs, src/backend/Core/Migrations/20230213210217_AddProductData.Designer.cs, src/backend/Core/Migrations/20230213210217_AddProductData.cs
=> Cu 862j58d1g fake data marcel pankanin

src/backend/Donate/DonateModule.cs, src/backend/Donate/Services/DonateNameBuilder/DonateNameBuilderService.cs, src/backend/DonateTests/Services/DonateNameBuilder/DonateNameBuilderServiceTests.cs
=> Added  DonateNameBuilder service and UnitTests for it

src/backend/Core/Setup/WebApi/ExceptionMiddlewareExtensions.cs, src/backend/Core/Setup/WebApi/WebApiBuilder.cs
=> Add exception handler

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginAction.cs, src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Auth/Actions/UserSettingsActions/GetUserDetails/GetUserDetailsService.cs, src/frontend/src/app/app.component.ts, src/frontend/src/app/enums/role.ts, src/frontend/src/app/interfaces/db-user.ts, src/frontend/src/app/pages/secure/user-settings/user-settings.component.html, src/frontend/src/app/pages/secure/user-settings/user-settings.component.scss, src/frontend/src/app/pages/secure/user-settings/user-settings.component.ts, src/frontend/src/app/pages/secure/user-settings/user-settings.module.ts, src/frontend/src/app/services/auth.service.ts
=> Add user settings screen

.github/actions/build-fe/action.yml, src/backend/Donate/DonateModule.cs, src/backend/Donate/Jobs/SetExpiredDonations/SetExpiredDonationsJob.cs, src/backend/Donate/Shared/ExpireDateService.cs, src/backend/DonateTests/Jobs/SetExpiredDonations/SetExpiredDonationsJobTests.cs, src/backend/WebApi/Controllers/Donate/MyDonationsController.cs, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/app/app.component.ts, src/frontend/src/app/pages/secure/layout/layout.module.ts, src/frontend/src/app/pages/secure/layout/navbar/navbar.component.html, src/frontend/src/app/pages/secure/layout/sidebar/sidebar.component.html, src/frontend/src/app/pages/secure/my-donation/models/donation-details-product.interface.ts, src/frontend/src/app/pages/secure/my-donation/models/donation-details-warehouse.interface.ts, src/frontend/src/app/pages/secure/my-donation/models/donation-details.interface.ts, src/frontend/src/app/pages/secure/my-donation/my-donation.component.html, src/frontend/src/app/pages/secure/my-donation/my-donation.component.ts, src/frontend/src/app/pages/secure/my-donation/my-donation.module.ts, src/frontend/src/app/pages/secure/my-donation/services/my-donation.service.ts, src/frontend/src/app/pages/secure/my-donations/models/my-donations-item.ts, src/frontend/src/app/pages/secure/my-donations/my-donations.component.html, src/frontend/src/app/pages/secure/my-donations/my-donations.component.ts, src/frontend/src/app/pages/secure/my-donations/my-donations.module.ts, src/frontend/src/app/pages/secure/my-donations/services/my-donations.service.ts, src/frontend/src/environments/environment.prod.ts, src/frontend/src/environments/environment.ts, src/frontend/src/index.html
=> Create my donation screen

.github/actions/build-fe/action.yml, .github/workflows/build-test-all.yml
=> feat(infra): fix gmaps scret

src/backend/Donate/Actions/DonateForm/GetProducts/GetProductsAction.cs, src/backend/Donate/Actions/DonateForm/GetProducts/GetProductsModule.cs, src/backend/Donate/Actions/DonateForm/GetProducts/GetProductsResponse.cs, src/backend/Donate/Actions/DonateForm/GetProducts/GetProductsService.cs, src/backend/Donate/DonateModule.cs, src/backend/DonateTests/Services/GetProductsTest/GetProductsActionTest.cs, src/backend/DonateTests/Services/GetWarehousesTest/GetWarehousesActionTests.cs, src/backend/WebApi/Controllers/Donate/DonateFormController.cs
=> Create GetProducts action/service 

src/backend/Donate/Actions/DonateForm/PerformDonate/PerformDonatePayload.cs, src/backend/Donate/Actions/DonateForm/PerformDonate/PerformDonateProductPayload.cs, src/backend/Donate/Actions/DonateForm/PerformDonate/PerformDonateResponse.cs, src/backend/Donate/Actions/MyDonations/GetListMyDonations/GetListMyDonationAction.cs, src/backend/Donate/Actions/MyDonations/GetListMyDonations/GetListMyDonationModule.cs, src/backend/Donate/Actions/MyDonations/GetListMyDonations/GetListMyDonationService.cs, src/backend/Donate/Actions/MyDonations/GetListMyDonations/GetListMyDonationsItemResponse.cs, src/backend/Donate/DonateModule.cs, src/backend/DonateTests/Services/GetListMyDonationsTest/GetListMyDonationActionTest.cs, src/backend/WebApi/Controllers/Donate/MyDonationsController.cs
=> Create myDonation endpoint with service and tests

src/backend/Donate/Actions/MyDonations/GetScore/GetScoreAction.cs, src/backend/Donate/Actions/MyDonations/GetScore/GetScoreModule.cs, src/backend/Donate/DonateModule.cs, src/backend/DonateTests/Actions/GetListMyDonationActionTest/GetListMyDonationActionTest.cs, src/backend/DonateTests/Actions/GetNotDeliveredCountActionTest/GetNotDeliveredCountActionTest.cs, src/backend/DonateTests/Actions/GetProductsActionTest/GetProductsActionTest.cs, src/backend/DonateTests/Actions/GetScoreActionTest/GetScoreActionTest.cs, src/backend/DonateTests/Actions/GetWarehousesActionTests/GetWarehousesActionTests.cs, src/backend/DonateTests/Actions/PerformDonateActionTest/PerformDonateActionTest.cs, src/backend/WebApi/Controllers/Donate/MyDonationsController.cs
=> Added GetScore endpoint

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/AuthTests/Actions/AuthActionsTest/PostLogin/PostLoginActionTests.cs, src/backend/AuthTests/Actions/UserSettingsTests/GetAuth0UsersByCurrentUser/GetAuth0UsersByCurrentUserActionTests.cs, src/backend/AuthTests/Actions/UserSettingsTests/GetCurrentUser/GetCurrentUserActionTest.cs, src/backend/AuthTests/Actions/UserSettingsTests/PatchUserDetails/PatchUserDetailsActionTest.cs, src/backend/Core/Database/Config/Models/Auth/UserConfig.cs, src/backend/Core/Database/Models/Auth/User.cs, src/backend/Core/Database/Models/Core/Warehouse.cs, src/backend/Core/Migrations/20230301175113_AddWarehouseIdToUserTable.Designer.cs, src/backend/Core/Migrations/20230301175113_AddWarehouseIdToUserTable.cs, src/backend/CoreTests/Services/RoleServiceTests.cs, src/backend/DonateTests/Actions/GetListMyDonationActionTest/GetListMyDonationActionTest.cs, src/backend/DonateTests/Actions/GetMyDonationDetailsActionTest/GetMyDonationDetailsActionTest.cs, src/backend/DonateTests/Actions/GetNotDeliveredCountActionTest/GetNotDeliveredCountActionTest.cs, src/backend/DonateTests/Actions/GetScoreActionTest/GetScoreActionTest.cs, src/backend/DonateTests/Actions/PerformDonateActionTest/PerformDonateActionTest.cs
=> Added warehouseId to User model, added new migration

src/backend/Donate/Actions/MyDonations/GetNotDeliveredCount/GetNotDeliveredCountAction.cs
=> BugFix Showing all notDeliveredDonations

src/backend/Core/Setup/SetupModule.cs, src/backend/Core/Setup/WebApi/Auth/WebApiAuth0UserFetchService.cs, src/backend/Core/Setup/WebApi/Auth/WebApiCurrentUserService.cs, src/backend/Core/Setup/WebApi/WebApiBuilder.cs, src/frontend/src/app/app.component.ts
=> Fix too many requests error

src/frontend/src/app/pages/secure/manage-users/manage-users.component.html, src/frontend/src/app/pages/secure/manage-users/manage-users.component.ts, src/frontend/src/app/pages/secure/manage-users/manage-users.module.ts, src/frontend/src/app/pages/secure/manage-users/models/manage-users-item.ts, src/frontend/src/app/pages/secure/manage-users/services/manage-users.service.ts
=> Manage users screen

src/backend/Auth/Actions/AuthActions/ManageUsersActions/ManageUsersAction.cs, src/backend/Auth/Actions/AuthActions/ManageUsersActions/ManageUsersModule.cs, src/backend/Auth/Actions/AuthActions/ManageUsersActions/ManageUsersResponseItem.cs, src/backend/Auth/AuthModule.cs, src/backend/AuthTests/Actions/AuthActionsTest/ManageUsersActionsTest/ManageUsersActionFixture.cs, src/backend/AuthTests/Actions/AuthActionsTest/ManageUsersActionsTest/ManageUsersActionTest.cs, src/backend/WebApi/Controllers/Auth/ManageUsersController.cs
=> Added manage-users endpoint with Intergration Tests

src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetList/ManageUsersGetListAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleResponseItem.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleModule.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSinglePayload.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleResponseItem.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleService.cs, src/backend/Auth/AuthModule.cs, src/backend/AuthTests/Actions/ManageUsersActionsTest/GetSingleTest/GetSingleActionTest.cs, src/backend/AuthTests/Actions/ManageUsersActionsTest/PatchSingleTest/PatchSingleActionFixture.cs, src/backend/AuthTests/Actions/ManageUsersActionsTest/PatchSingleTest/PatchSingleActionTest.cs, src/backend/WebApi/Controllers/Auth/ManageUsersController.cs
=> create PatchSIngle endpoint, create Integration Tests

src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleService.cs, src/backend/Donate/Actions/DonateForm/GetWarehouses/GetWarehousesService.cs, src/backend/DonateTests/Actions/GetWarehousesActionTests/GetWarehousesActionTests.cs, src/backend/Order/Actions/WarehousesActions/WarehousesGetList/WarehousesGetListAction.cs, src/backend/Order/Actions/WarehousesActions/WarehousesGetList/WarehousesGetListModule.cs, src/backend/Order/Actions/WarehousesActions/WarehousesGetList/WarehousesGetListResponse.cs, src/backend/Order/OrderModule.cs, src/backend/OrderTests/Actions/WarehousesActionTest/WarehousesGetListActionTest.cs, src/backend/WebApi/Controllers/Order/WarehousesController.cs, src/backend/WebApi/UsedModules.cs, src/backend/WebApi/WebApi.csproj
=> Create endpoint warehouses

src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetList/ManageUsersGetListAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetList/ManageUsersGetListResponseItem.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleResponseItem.cs, src/backend/AuthTests/Actions/ManageUsersActionsTest/GetListTest/GetListActionTest.cs, src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Config/Models/Core/NotificationConfig.cs, src/backend/Core/Database/Models/Auth/User.cs, src/backend/Core/Database/Models/Core/Notification.cs, src/backend/Core/Migrations/20230306124158_AddNotificationsTable.Designer.cs, src/backend/Core/Migrations/20230306124158_AddNotificationsTable.cs
=> Create notifications table 

src/backend/AuthTests/Actions/ManageUsersActionsTest/GetListTest/GetListActionFixture.cs, src/backend/AuthTests/Actions/ManageUsersActionsTest/PatchSingleTest/PatchSingleActionFixture.cs, src/backend/Core/Actions/MyNotifications/MyNotificationsGetListLast30DaysAction.cs, src/backend/Core/Actions/MyNotifications/MyNotificationsGetListLast30DaysModule.cs, src/backend/Core/Actions/MyNotifications/MyNotificationsGetListLast30DaysResponseItem.cs, src/backend/Core/Core.csproj, src/backend/Core/CoreModule.cs, src/backend/Core/Database/Config/Models/Core/NotificationConfig.cs, src/backend/Core/Database/Models/Core/Notification.cs, src/backend/Core/Migrations/20230306150840_AddColumnCreationDateToNotifications.Designer.cs, src/backend/Core/Migrations/20230306150840_AddColumnCreationDateToNotifications.cs, src/backend/CoreTests/Actions/MyNotificationsGetListLast30DaysTest/MyNotificationsGetListLast30DaysActionTest.cs, src/backend/CoreTests/Actions/MyNotificationsGetListLast30DaysTest/MyNotificationsGetListLast30DaysFixture.cs, src/backend/WebApi/Controllers/Core/MyNotificationsController.cs
=> Create myNotifications endpoint

src/backend/AuthTests/Actions/ManageUsersActionsTest/PatchSingleTest/PatchSingleActionFixture.cs, src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationAction.cs, src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationModule.cs, src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationService.cs, src/backend/Donate/DonateModule.cs, src/backend/DonateTests/Actions/PostPickUpDonationActionTest/PostPickupDonationActionFixture.cs, src/backend/DonateTests/Actions/PostPickUpDonationActionTest/PostPickupDonationActionTest.cs, src/backend/WebApi/Controllers/Donate/PickUpDonationController.cs
=> Add new PickupDonation endpoint, service and integration tests

.github/actions/sonar/action.yml, .github/actions/test-int-be/action.yml, .github/workflows/build-test-all.yml
=> feat(infra): move sonar

src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Config/Models/Core/StockConfig.cs, src/backend/Core/Database/Models/Core/Product.cs, src/backend/Core/Database/Models/Core/Stock.cs, src/backend/Core/Migrations/20230307181910_AddStocksTable.Designer.cs, src/backend/Core/Migrations/20230307181910_AddStocksTable.cs
=> added Stock table to database, added new migration

.github/actions/sonar/action.yml, src/backend/Order/OrderModule.cs, src/backend/Order/Services/OrderNameBuilder/OrderNameBuilderService.cs, src/backend/OrderTests/Services/OrderNameBuilder/OrderNameBuilderServiceTests.cs
=> Order Name builder

src/backend/Donate/DonateModule.cs, src/backend/Donate/Jobs/IncludeToStock/IncludeToStockJob.cs, src/backend/Donate/Jobs/IncludeToStock/IncludeToStockModule.cs, src/backend/DonateTests/Jobs/IncludeToStock/IncludeToStockJobFixture.cs, src/backend/DonateTests/Jobs/IncludeToStock/IncludeToStockJobTests.cs, src/backend/Worker/Controllers/DonateJobs.cs
=> Create includeToStock job, with integration tests

src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListAction.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListItemResponse.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListModule.cs, src/backend/Order/Actions/WarehousesActions/WarehousesGetList/WarehousesGetListAction.cs, src/backend/Order/OrderModule.cs, src/backend/OrderTests/Actions/StockActoinTest/StocksGetListActionFixture.cs, src/backend/OrderTests/Actions/StockActoinTest/StocksGetListActionTest.cs, src/backend/WebApi/Controllers/Order/StocksController.cs
=> Added stocks endpoint, with integration tests

src/backend/Order/OrderModule.cs, src/backend/Order/Services/DeliveryNameBuilder/DeliveryNameBuilderService.cs, src/backend/OrderTests/Services/DeliveryNameBuilder/OrderNameBuilderServiceTests.cs
=> add DeliveryNameBuilder

infra/terraform/modules/ingoodhands/modules/basics/worker.tf
=> feat(infra): include to stock job

src/backend/Core/Database/AppDbContext.cs, src/backend/Core/Database/Config/Models/Core/DeliveryConfig.cs, src/backend/Core/Database/Config/Models/Core/DeliveryProductConfig.cs, src/backend/Core/Database/Config/Models/Core/NotificationConfig.cs, src/backend/Core/Database/Config/Models/Core/OrderConfig.cs, src/backend/Core/Database/Config/Models/Core/OrderProductConfig.cs, src/backend/Core/Database/Models/Auth/User.cs, src/backend/Core/Database/Models/Core/Address.cs, src/backend/Core/Database/Models/Core/Delivery.cs, src/backend/Core/Database/Models/Core/DeliveryProduct.cs, src/backend/Core/Database/Models/Core/Order.cs, src/backend/Core/Database/Models/Core/OrderProduct.cs, src/backend/Core/Database/Models/Core/Product.cs, src/backend/Core/Database/Models/Core/Warehouse.cs, src/backend/Core/Migrations/20230309185917_AddOrderAndDeliveryTables.Designer.cs, src/backend/Core/Migrations/20230309185917_AddOrderAndDeliveryTables.cs
=> Create Order and delivery tables, add migration

src/backend/Core/Database/Config/Models/Core/UserAddressConfig.cs, src/backend/Core/Database/Models/Auth/User.cs, src/backend/Core/Database/Models/Core/UserAddress.cs, src/backend/Core/Migrations/20230310141800_AddUserAddressesTable.Designer.cs, src/backend/Core/Migrations/20230310141800_AddUserAddressesTable.cs
=> create userAddresses table, added new migration

src/frontend/src/app/pages/home/work/work.component.html, src/frontend/src/app/pages/secure/start/start.component.html, src/frontend/src/app/pages/secure/work/work.component.html
=> Change work screen

src/backend/Order/Actions/CreateOrderActions/CreateOrderGetCountries/CreateOrderGetCountriesAction.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetCountries/CreateOrderGetCountriesModule.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetCountries/CreateOrderGetCountriesService.cs, src/backend/Order/OrdersModule.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetCountriesActionTest.cs, src/backend/WebApi/Controllers/Order/CreateOrderController.cs
=> Create CreateOrder GetCountries endpoint, integration test

src/backend/Donate/Jobs/IncludeToStock/IncludeToStockJob.cs
=> IncludeToStock bug fix

src/frontend/src/app/pages/secure/manage-user/manage-user.component.html, src/frontend/src/app/pages/secure/manage-user/manage-user.component.scss, src/frontend/src/app/pages/secure/manage-user/manage-user.component.ts, src/frontend/src/app/pages/secure/manage-user/models/manage-user-details.ts, src/frontend/src/app/pages/secure/manage-users/manage-users.component.html, src/frontend/src/app/pages/secure/manage-users/manage-users.component.scss, src/frontend/src/app/pages/secure/manage-users/models/manage-users-item.ts
=> Add email to manage users

src/backend/Order/Actions/CreateOrderActions/CreateOrderGetAddresses/CreateOrderGetAddressesAction.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetAddresses/CreateOrderGetAddressesItemResponse.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetAddresses/CreateOrderGetAddressesModule.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetAddresses/CreateOrderGetAddressesService.cs, src/backend/Order/OrdersModule.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderAddAddressActionTest/CreateOrderAddAddressActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetAddressesActionTest/CreateOrderGetAddressesActionFixture.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetAddressesActionTest/CreateOrderGetAddressesActionTest.cs, src/backend/WebApi/Controllers/Order/CreateOrderController.cs
=> Add GetAddresses endpoint, integration tests

src/backend/Core/Database/Enums/TableName.cs, src/backend/Core/Database/Seeders/CounterSeeder.cs, src/backend/Core/Migrations/20230315124234_UpdateCounterTable.Designer.cs, src/backend/Core/Migrations/20230315124234_UpdateCounterTable.cs, src/backend/Core/Services/CounterService.cs, src/backend/CoreTests/Services/CounterServiceTests.cs, src/backend/Donate/Actions/DonateForm/PerformDonate/PerformDonateService.cs, src/backend/DonateTests/Actions/PerformDonateActionTest/PerformDonateActionTest.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderAddAddress/CreateOrderAddAddressService.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderAction.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderModule.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderPayload.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderPayloadValidator.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderProductPayload.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderResponse.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderService.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderDeleteAddress/CreateOrderDeleteAddressService.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetAddresses/CreateOrderGetAddressesService.cs, src/backend/Order/Actions/CreateOrderActions/CreateOrderGetCountries/CreateOrderGetCountriesService.cs, src/backend/Order/OrdersModule.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderAddAddressActionTest/CreateOrderAddAddressActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderCreateOrderActionTest/CreateOrderCreateOrderActionFixture.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderCreateOrderActionTest/CreateOrderCreateOrderActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderDeleteAddressActionTest/CreateOrderDeleteAddressActionFixture.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderDeleteAddressActionTest/CreateOrderDeleteAddressActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetAddressesActionTest/CreateOrderGetAddressesActionFixture.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetAddressesActionTest/CreateOrderGetAddressesActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetCountriesActionTest/CreateOrderGetCountriesActionTest.cs, src/backend/OrderTests/Actions/CreateOrderActionTest/CreateOrderGetCountriesActionTest/CreateOrderGetCountriesFixture.cs, src/backend/WebApi/Controllers/Order/CreateOrderController.cs
=> Add CreateOrder post endpoint, integration tests, and few fixes

src/frontend/.gitignore
=> Force update

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Core/Database/Config/Models/Core/DeliveryConfig.cs, src/backend/Core/Database/Models/Core/Order.cs, src/backend/Core/Migrations/20230316174442_UpdateOrderDeliveryRelation.Designer.cs, src/backend/Core/Migrations/20230316174442_UpdateOrderDeliveryRelation.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleAction.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleDeliveryResponse.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleItemResponse.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleModule.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleProductResponse.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleResponse.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/backend/Order/OrdersModule.cs, src/backend/OrderTests/Actions/OrdersActionTest/OrdersGetSingleActionFixture.cs, src/backend/OrderTests/Actions/OrdersActionTest/OrdersGetSingleActionTest.cs, src/backend/WebApi/Controllers/Order/OrdersController.cs
=> Add Orders Get Single endpoint with integration tests

src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/frontend/src/app/pages/secure/order/interfaces/orders-get-single-response.ts, src/frontend/src/app/pages/secure/order/order.component.html, src/frontend/src/app/pages/secure/order/order.component.ts, src/frontend/src/app/pages/secure/order/order.module.ts, src/frontend/src/app/pages/secure/order/services/order.service.ts, src/frontend/src/app/pipes/string2date/string2date.module.ts, src/frontend/src/app/pipes/string2date/string2date.pipe.ts
=> Order screen

src/backend/Order/Actions/OrdersActions/OrdersCancel/OrdersCancelAction.cs, src/backend/Order/Actions/OrdersActions/OrdersCancel/OrdersCancelModule.cs, src/backend/Order/Actions/OrdersActions/OrdersCancel/OrdersCancelService.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleAction.cs, src/backend/Order/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/backend/Order/OrdersModule.cs, src/backend/OrderTests/Actions/OrdersActionTest/OrdersCancelActionFixture.cs, src/backend/OrderTests/Actions/OrdersActionTest/OrdersCancelActionTest.cs, src/backend/WebApi/Controllers/Order/OrdersController.cs
=> Added Orders Cancel endpoint, integration tests

src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleService.cs, src/backend/Core/Services/RoleService.cs, src/backend/DonateTests/Actions/GetListMyDonationActionTest/GetListMyDonationActionTest.cs, src/backend/DonateTests/Actions/GetMyDonationDetailsActionTest/GetMyDonationDetailsActionTest.cs, src/backend/DonateTests/Actions/GetNotDeliveredCountActionTest/GetNotDeliveredCountActionTest.cs, src/backend/DonateTests/Actions/GetScoreActionTest/GetScoreActionTest.cs
=> Review and FIX of UpdateUserId & UpdatedAt

src/backend/Core/Database/Config/Models/Core/StockConfig.cs, src/backend/Core/Database/Models/Core/Stock.cs, src/backend/Core/Database/Models/Core/Warehouse.cs, src/backend/Core/Migrations/20230317153751_UpdateStockTable.Designer.cs, src/backend/Core/Migrations/20230317153751_UpdateStockTable.cs, src/backend/Donate/Jobs/IncludeToStock/IncludeToStockJob.cs, src/backend/Donate/Jobs/IncludeToStock/StockKeyEqualityComparer.cs, src/backend/DonateTests/Jobs/IncludeToStock/IncludeToStockJobFixture.cs, src/backend/DonateTests/Jobs/IncludeToStock/IncludeToStockJobTest.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListAction.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListItemResponse.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListModule.cs, src/backend/Order/Actions/StocksActions/StocksGetList/StocksGetListService.cs, src/backend/OrderTests/Actions/Stock/StocksGetListFixture.cs, src/backend/OrderTests/Actions/Stock/StocksGetListTest.cs
=> Add warehouse to Stock, apply changes, fix tests

src/backend/Core/Database/Config/Models/Core/StockConfig.cs
=> update stock config

src/backend/Core/Database/Config/Models/Core/UserWebPushConfig.cs, src/backend/Core/Migrations/20230317180326_ChangeWebPushPropLength.Designer.cs, src/backend/Core/Migrations/20230317180326_ChangeWebPushPropLength.cs, src/frontend/src/app/app.component.ts
=> Fix edge error

firebase.json, infra/terraform/modules/ingoodhands/modules/basics/worker.tf, src/frontend/ngsw-config.json
=> feat(infra): two jobs scheduled

src/backend/Core/Actions/WarehouseName/GetWarehouseName/GetWarehouseNameAction.cs, src/backend/Core/Actions/WarehouseName/GetWarehouseName/GetWarehouseNameModule.cs, src/backend/Core/Actions/WarehouseName/GetWarehouseName/GetWarehouseNameResponse.cs, src/backend/Core/Actions/WarehouseName/GetWarehouseName/GetWarehouseNameService.cs, src/backend/Core/CoreModule.cs, src/backend/Core/Services/GetCurrentUserService.cs, src/backend/CoreTests/Actions/GetWarehouseName/GetWarehouseNameFixture.cs, src/backend/CoreTests/Actions/GetWarehouseName/GetWarehouseNameTest.cs, src/backend/WebApi/Controllers/Order/DeliveriesController.cs, src/backend/WebApi/Controllers/Order/StocksController.cs
=> Added new shared endpoint to Deliveries and Stocks controller,IT

src/backend/Core/Database/Config/Models/Core/DeliveryConfig.cs, src/backend/Core/Database/Models/Core/Delivery.cs, src/backend/Core/Migrations/20230405170354_ChangeColumnNameOnTableDeliveries.Designer.cs, src/backend/Core/Migrations/20230405170354_ChangeColumnNameOnTableDeliveries.cs, src/backend/OrdersTests/Actions/Orders/OrdersCancelFixture.cs, src/backend/OrdersTests/Actions/Orders/OrdersGetSingleFixture.cs
=> Changed name of the column in deliveries table

src/backend/Core/Database/Config/Models/Core/OrderConfig.cs, src/backend/Core/Database/Models/Core/Order.cs, src/backend/Core/Migrations/20230420132956_NewOrderProperty.Designer.cs, src/backend/Core/Migrations/20230420132956_NewOrderProperty.cs, src/backend/Orders/Actions/CreateOrderActions/CreateOrderCreateOrder/CreateOrderCreateOrderService.cs, src/backend/Orders/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJob.cs, src/backend/Orders/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJobDataService.cs, src/backend/Orders/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJobModule.cs, src/backend/Orders/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJobService.cs, src/backend/Orders/OrdersModule.cs, src/backend/OrdersTests/Jobs/CreateDeliveries/CreateDeliveriesJobFixture.cs, src/backend/OrdersTests/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJobFixture.cs, src/backend/OrdersTests/Jobs/RecalcOrdersPercentage/RecalcOrdersPercentageJobTest.cs
=> Add recalcOrderPercentageJob, integrationTests

src/backend/Orders/Jobs/CreateDeliveries/CreateDeliveriesJobWarehouseService.cs
=> Send notifications upon creating deliveries

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Auth/Services/CurrentUserInfoValidator.cs, src/backend/AuthTests/Actions/Auth/PostLoginTest.cs
=> Fix email verification

src/backend/Core/Actions/DonateForm/GetProducts/GetProductsService.cs, src/backend/Core/Database/Seeders/ProductSeeder.cs, src/backend/Core/Migrations/20230426163945_AddMoreProductsToSeeder.Designer.cs, src/backend/Core/Migrations/20230426163945_AddMoreProductsToSeeder.cs, src/backend/Donate/Actions/DonateForm/GetWarehouses/GetWarehousesAction.cs
=> Add defensive products to database

src/backend/Core/Actions/WarehouseName/GetWarehouseName/GetWarehouseNameService.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetSingle/DeliveriesGetSingleService.cs, src/frontend/src/app/app.component.scss, src/frontend/src/app/pages/secure/deliveries/services/deliveries.service.ts, src/frontend/src/app/pages/secure/stocks/services/stocks.service.ts, src/frontend/src/app/services/http-error-interceptor.ts
=> Minor fixes

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetList/ManageUsersGetListAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetList/ManageUsersGetListResponseItem.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleAction.cs, src/backend/Auth/Actions/ManageUsersActions/ManageUsersGetSingle/ManageUsersGetSingleResponseItem.cs, src/backend/Core/Database/Config/Models/Auth/Auth0UserConfig.cs, src/backend/Core/Database/Models/Auth/Auth0User.cs, src/backend/Core/Migrations/20230426203633_AddPictureUrl.Designer.cs, src/backend/Core/Migrations/20230426203633_AddPictureUrl.cs, src/backend/Worker/UsedModules.cs, src/frontend/src/app/pages/secure/manage-user/manage-user.component.html, src/frontend/src/app/pages/secure/manage-user/manage-user.component.scss, src/frontend/src/app/pages/secure/manage-user/manage-user.component.ts, src/frontend/src/app/pages/secure/manage-user/models/manage-user-details.ts, src/frontend/src/app/pages/secure/manage-users/interfaces/manage-users-item.ts, src/frontend/src/app/pages/secure/manage-users/manage-users.component.html, src/frontend/src/app/pages/secure/manage-users/manage-users.component.scss, src/frontend/src/app/services/auth.service.ts
=> Fixes for E2E

src/backend/WebApi/Controllers/Order/AvailableDeliveriesController.cs, src/backend/WebApi/Controllers/Order/CurrentDeliveryController.cs, src/frontend/src/app/pages/secure/available-deliveries/available-deliveries.component.ts, src/frontend/src/app/pages/secure/current-delivery/current-delivery.component.html, src/frontend/src/app/pages/secure/current-delivery/current-delivery.component.ts, src/frontend/src/app/pages/secure/current-delivery/interfaces/current-delivery-get-single-response.ts, src/frontend/src/app/pages/secure/current-delivery/services/current-delivery.service.ts, src/frontend/src/app/pages/secure/my-donations/my-donations.component.html, src/frontend/src/app/pages/secure/my-donations/my-donations.component.ts
=> Add current delivery screen

src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesCount/AvailableDeliveriesCountAction.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesCount/AvailableDeliveriesCountModule.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesCount/AvailableDeliveriesCountResponse.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesCount/AvailableDeliveriesCountService.cs, src/backend/Orders/OrdersModule.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesCountFixture.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesCountTest.cs, src/backend/WebApi/Controllers/Order/AvailableDeliveriesController.cs
=> Add count endpoint for availableControler + IT

src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleAction.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleLocationResponse.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleModule.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleProductResponse.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleResponse.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleService.cs, src/backend/Orders/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/backend/Orders/OrdersModule.cs, src/backend/OrdersTests/Actions/CurrentDelivery/CurrentDeliveryGetSingleFixture.cs, src/backend/OrdersTests/Actions/CurrentDelivery/CurrentDeliveryGetSingleTest.cs, src/backend/WebApi/Controllers/Order/CurrentDeliveryController.cs
=> Add endpoint to CurrentDelivery controller + Integration tests

src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetWarehouseDeliveriesCount/DeliveriesGetWarehouseDeliveriesCountAction.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetWarehouseDeliveriesCount/DeliveriesGetWarehouseDeliveriesCountModule.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetWarehouseDeliveriesCount/DeliveriesGetWarehouseDeliveriesCountResponse.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetWarehouseDeliveriesCount/DeliveriesGetWarehouseDeliveriesCountService.cs, src/backend/Orders/OrdersModule.cs, src/backend/OrdersTests/Actions/Deliveries/DeliveriesGetWarehouseDeliveriesCountFixture.cs, src/backend/OrdersTests/Actions/Deliveries/DeliveriesGetWarehouseDeliveriesCountTest.cs, src/backend/WebApi/Controllers/Order/DeliveriesController.cs
=> Added endpoint to deliveries controller + Integration Tests

src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesAssignDelivery/AvailableDeliveriesAssignDeliveryAction.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesAssignDelivery/AvailableDeliveriesAssignDeliveryModule.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesAssignDelivery/AvailableDeliveriesAssignDeliveryService.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesGetList/AvailableDeliveriesGetListAction.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesGetList/AvailableDeliveriesGetListModule.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesGetList/AvailableDeliveriesGetListResponse.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesGetList/AvailableDeliveriesGetListService.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryAction.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryModule.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryResponse.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryService.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesPickup/DeliveriesPickupAction.cs, src/backend/Orders/OrdersModule.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesAssignDeliveryFixture.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesAssignDeliveryTest.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesGetListFixture.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesGetListTest.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesHasActiveDeliveryFixture.cs, src/backend/OrdersTests/Actions/AvailableDeliveries/AvailableDeliveriesHasActiveDeliveryTest.cs, src/backend/WebApi/Controllers/Order/AvailableDeliveriesController.cs
=> Add extra notifications + endpoint in availableController

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Auth/Actions/ManageUsersActions/ManagerUsersPatchSingle/ManageUsersPatchSingleService.cs, src/backend/Core/Actions/MyNotifications/GetList/MyNotificationsGetListLast30DaysAction.cs, src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationService.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryService.cs, src/frontend/src/app/pages/secure/delivery/delivery.component.html, src/frontend/src/app/pages/secure/manage-user/manage-user.component.ts
=> Fixes after E2E 2

src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationService.cs, src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleService.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesPickup/DeliveriesPickupAction.cs, src/backend/Orders/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/backend/Orders/Actions/StocksActions/StocksGetList/StocksGetListService.cs, src/backend/Orders/Jobs/CreateDeliveries/CreateDeliveriesJobWarehouseService.cs, src/backend/OrdersTests/Actions/CurrentDelivery/CurrentDeliveryGetSingleFixture.cs
=> Fixes after E2E 3

src/backend/Donate/Actions/PickUpDonation/PostPickUpDonation/PostPickupDonationService.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesAssignDelivery/AvailableDeliveriesAssignDeliveryService.cs, src/backend/Orders/Actions/AvailableDeliveriesActions/AvailableDeliveriesHasActiveDelivery/AvailableDeliveriesHasActiveDeliveryService.cs, src/backend/Orders/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleDeliveryResponse.cs, src/backend/Orders/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/backend/Worker/Controllers/OrderJobsController.cs, src/frontend/src/app/pages/secure/current-delivery/current-delivery.component.ts, src/frontend/src/app/pages/secure/my-donations/my-donations.component.ts, src/frontend/src/app/pages/secure/order/interfaces/orders-get-single-response.ts, src/frontend/src/app/pages/secure/order/order.component.html, src/frontend/src/app/pages/secure/order/order.component.ts
=> Fixes after E2E 4

src/backend/Orders/Actions/CurrentDelivery/CurrentDeliveryGetSingle/CurrentDeliveryGetSingleService.cs, src/backend/Orders/Actions/OrdersActions/OrdersGetSingle/OrdersGetSingleService.cs, src/frontend/src/app/pages/secure/delivery/delivery.component.html
=> Fixes after E2E 5

src/backend/Auth/Actions/AuthActions/PostLogin/PostLoginUserCreationService.cs, src/backend/Auth/Models/UserDetailsResponse.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesGetList/DeliveriesGetListService.cs, src/backend/Orders/Actions/DeliveriesActions/DeliveriesPickup/DeliveriesPickupAction.cs, src/backend/OrdersTests/Actions/Deliveries/DeliveriesGetListFixture.cs, src/backend/OrdersTests/Actions/Deliveries/DeliveriesGetListTest.cs, src/frontend/src/app/interfaces/db-user.ts, src/frontend/src/app/pages/secure/layout/sidebar/sidebar.component.html, src/frontend/src/app/pages/secure/layout/sidebar/sidebar.component.scss, src/frontend/src/app/pages/secure/layout/sidebar/sidebar.component.ts
=> Filter deliveries from deliverer warehouse only

src/backend/Core/Actions/MyNotifications/TestWebPush/MyNotificationsTestWebPushAction.cs, src/backend/Core/Actions/MyNotifications/TestWebPush/MyNotificationsTestWebPushModule.cs, src/backend/Core/Actions/MyNotifications/TestWebPush/MyNotificationsTestWebPushResponse.cs, src/backend/Core/CoreModule.cs, src/backend/CoreTests/Actions/MyNotificationsTestWebPush/MyNotificationsTestWebPushFixture.cs, src/backend/CoreTests/Actions/MyNotificationsTestWebPush/MyNotificationsTestWebPushTest.cs, src/backend/CoreTests/Actions/MyNotificationsUpdateWebPush/MyNotificationsUpdateWebPushTest.cs, src/backend/WebApi/Controllers/Core/MyNotificationsController.cs, src/frontend/src/app/app.component.ts, src/frontend/src/app/app.module.ts, src/frontend/src/app/pages/secure/layout/navbar/navbar.component.ts, src/frontend/src/app/pages/secure/layout/sidebar/sidebar-config.ts, src/frontend/src/app/pages/secure/layout/sidebar/sidebar.component.ts, src/frontend/src/app/pages/secure/user-settings/user-settings.component.html, src/frontend/src/app/pages/secure/user-settings/user-settings.component.ts, src/frontend/src/app/services/auth.service.ts, src/frontend/src/app/services/notifications.service.ts
=> Final adjustments

src/backend/Orders/Jobs/CreateDeliveries/CreateDeliveriesJobWarehouseService.cs, src/frontend/src/app/pages/secure/order/order.component.html
=> Test fixes
